[Model]
ProjectName                                     =  SP2D07XF0_KBC_Test
Version                                             = V0.0.0.1
SFCNumber                                      = 006310

[MD5_INFO]
MD5_INFO                                        =e80f894ea511c922515373a57d824ada

#############The above configuration is fixed###############

#############Below you can add custom Settings#############


[KBC_Ver]
Version                                             = 107


[ICT_Flow]
ICT_FlowMark                                    = EVO
ICT_FlowMd5                                     = dbc87c82e5c865ba6d3670e2e397abad
