[Model]
ProjectName                                     = ZLogDataCollection_Litepoint_V1
Version                                             = V0.0.0.1
SFCNumber                                      = 007321


[MD5_INFO]
MD5_INFO                                        =1e6e027a8ef8ed5b703593dd45ca5ab4

##########################The above configuration is fixed###############################

##########################Below you can add custom Settings#############################
