[Model]
ProjectName                                     = SP2D08XF1_KBC_Test
Version                                             = V0.0.0.1
SFCNumber                                      = 006310

[MD5_INFO]
MD5_INFO                                        =a25b5bfb319dd0ab1b779fde555ea314

#############The above configuration is fixed###############

#############Below you can add custom Settings#############


[KBC_Ver]
Version                                             = 203

[ICT_Flow]
ICT_FlowMark                                    = EVO
ICT_FlowMd5                                     = dbc87c82e5c865ba6d3670e2e397abad
