[Model]
ProjectName                                     = ZLogDataCollection_Litepoint_V2
Version                                             = V0.0.0.1
SFCNumber                                      = 007321


[MD5_INFO]
MD5_INFO                                        =b634bc658a767683c925db1d3c1c90ad

##########################The above configuration is fixed###############################

##########################Below you can add custom Settings#############################
