[Model]
ProjectName                                     = SP2E04XB1_KBC_Test
Version                                             = V0.0.0.1
SFCNumber                                      = 00TBD

[MD5_INFO]
MD5_INFO                                        =28385e6621d26e6fa05349bd207548b4

#############The above configuration is fixed###############

#############Below you can add custom Settings#############


[KBC_Ver]
Version                                             = 203;1100


[ICT_Flow]
ICT_FlowMark                                    = 251121
ICT_FlowMd5                                     = 7657d639e4e31ea57937ced369de59e9
