[Model]
ProjectName                                     = ZLogDataCollection_ICT_V1
Version                                             = V0.0.0.1
SFCNumber                                      = 007321


[MD5_INFO]
MD5_INFO                                        =2968341d58b1857c4fa90e2f4876c1c1

##########################The above configuration is fixed###############################

##########################Below you can add custom Settings#############################
