[Model]
ProjectName                                     = SP2D08XF2_KBC_Test
Version                                             = V0.0.0.1
SFCNumber                                      = 00TBD

[MD5_INFO]
MD5_INFO                                        =f5931425a795e7c637162903c27ef497

#############The above configuration is fixed###############

#############Below you can add custom Settings#############


[KBC_Ver]
Version                                             = 203;1111


[ICT_Flow]
ICT_FlowMark                                    = EVO
ICT_FlowMd5                                     = dbc87c82e5c865ba6d3670e2e397abad
