[Model]
ProjectName                                     =  SP2D_General ICT
Version                                             = V0.0.0.1
SFCNumber                                      = TBD

[MD5_INFO]
MD5_INFO                                        =bc1ccc43d77f79d6491a6ef68d77c823

#############The above configuration is fixed###############

#############Below you can add custom Settings#############

[ICT_Flow]
ICT_FlowMark                                    = 250716
ICT_FlowMd5                                     = 86db4d9be7943c63719b968f0a33c985