[Model]
ProjectName                                     = SP2D07XF2_KBC_Test
Version                                             = V0.0.0.1
SFCNumber                                      = 00TBD

[MD5_INFO]
MD5_INFO                                        =a732f7b989cad63f390d5c03fde520ee

#############The above configuration is fixed###############

#############Below you can add custom Settings#############


[KBC_Ver]
Version                                             = 203;1111

[ICT_Flow]
ICT_FlowMark                                    = EVO
ICT_FlowMd5                                     = dbc87c82e5c865ba6d3670e2e397abad
