[Model]
ProjectName                                     = ZLogDataCollection_ACE_V1
Version                                             = V0.0.0.1
SFCNumber                                      = 007321


[MD5_INFO]
MD5_INFO                                        =4c285fec81dee11ef27056f99a318d92

##########################The above configuration is fixed###############################

##########################Below you can add custom Settings#############################
